### ISSUE TITLE
data file is too large

### ISSUE THREAD

**Issue by stephens999** [jhsiao999/ashlar#1]
i get this warning
remote: warning: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
remote: warning: See http://git.io/iEPt8g for more information.
remote: warning: File data/molecules-final.txt is 51.16 MB; this is larger than GitHub's recommended maximum file size of 50.00 MB

would seem best to keep the template example files minimal in size

**Comment by stephens999** [comment]
i see on slack that you removed the large data file. But of course it is still there in the repo!
You'll need to restart the repo, or prune it out using filter, like this:
https://help.github.com/articles/remove-sensitive-data/

**Comment by jhsiao999** [comment]
Done. I've rewritten the commit history using the following:

$ git filter-branch --force --index-filter  'git rm --cached --ignore-unmatch data/molecules-final.txt' \
--prune-empty --tag-name-filter cat -- --all
$ git commit --amend -CHEAD
$ git push -force -all
