### ISSUE TITLE
testit package needs installing

### ISSUE THREAD

**Issue by stephens999** [jhsiao999/ashlar#3]
when i type make in the analysis subdir i get an error that testit is not installed.
Probably should include a list of packages they need to install in the instructions.
(And minimize the number that are required...).

Quitting from lines 60-61 (single-cell-pca.Rmd) 
Error in library("testit") : there is no package called 'testit'

(Maybe this example can be simplified so that testit is not required?)

**Comment by jhsiao999** [comment]
The assert function in testit was originally used in the PCA functions to generate a message in case of an error. I removed from function.R any dependency on testit.
