### ISSUE TITLE
need instructions on what needs editing to make the website work for the new repo

### ISSUE THREAD

**Issue by stephens999** [jhsiao999/ashlar#4]
as it is, after following the instructinos, 
the title of index.html is still ashlar, and github links to the original repo,
not the new repo... 

can we add instructions to say what needs changing to make the website work?

**Comment by stephens999** [comment]
seems the main thing I needed to change is 
include/before_body.html

**Comment by jhsiao999** [comment]
See the new instructions in the readme:

https://github.com/jhsiao999/ashlar
