### ISSUE TITLE
path 1 problem?

### ISSUE THREAD

**Issue by stephens999** [jhsiao999/ashlar#6]
not sure about path 1 in the README

when you checkout master and then merge gh-pages won't that add the html files
to master? That isn't what you want right?

I'm not 100% sure, but I think it is best to work in the master branch. Then when you are done with a new analysis commit it, and then switch to gh-pages, merge and add the html before committing.

**Comment by jhsiao999** [comment]
Yeah you are right. git merge by passes .gitignore. Therefore, when we merge gh-pages into the master branch, all the htmls that are in the gh-pages branch are copied over. I've removed path 1 from the README.
