### ISSUE TITLE
mathjax problem

### ISSUE THREAD

**Issue by stephens999** [jhsiao999/ashlar#9]
the mathjax = null in analysis/_output.yaml causes problems when rendering math in html

**Comment by jhsiao999** [comment]
The problem should be fixed now with "mathjax: default".

MathJax is a Java script for displaying mathematical notations that are written in LaText and MathML in a web browser. We can control how MathJax is included in _output.yaml. 

"mathjax: default" includes the MathJax code in the html. This option requires online access.
"mathjax: null" does not include MathJax code in the html. Some of your mathematical notations may not be displayed properly.
